version: '3'

networks:
  monitoring:
    driver: bridge

services:
  redis-server:
    image: 'redis'
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - monitoring

  node-app:
    build: .
    container_name: koa
    ports:
      - "8080:3000"
    image: koa:latest
    networks:
      - monitoring
  
  prometheus-mon:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    restart: unless-stopped
    networks:
      - monitoring
