version: '3'

services:
  redis-server:
    image: 'redis'
    container_name: redis    
    ports:
      - "6379:6379"

  cadvisor-redis:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor-redis
    ports:
    - 8081:8080
    depends_on:
    - redis-server

  cadvisor-koa:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor-koa
    ports:
    - 8082:8080
    depends_on:
    - web-app

  web-app:
    build: .
    container_name: koa
    ports:
      - "8080:3000"    
    image: koa:latest
    environment:
      - REDIS_ADDRESS=redis
 
  prometheus-mon:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    restart: unless-stopped
    depends_on:
    - cadvisor-redis
    - cadvisor-koa
