version: '3'

services:
  redis-server:
    image: 'redis'
    container_name: redis    
    ports:
      - "6379:6379"

  web-app:
    build: .
    container_name: koa
    ports:
      - "8080:3000"    
    image: koa:latest
    environment:
      - REDIS_ADDRESS=redis
  
  prometheus-mon:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    restart: unless-stopped
