global:
  scrape_interval: 30s
  scrape_timeout: 10s

scrape_configs:

  - job_name: redis
    scrape_interval: 5s
    static_configs:
    - targets:
      - cadvisor-redis:8080

  - job_name: webapp
    scrape_interval: 5s
    static_configs:
    - targets:
      - cadvisor-koa:8080
