global:
  scrape_interval: 30s
  scrape_timeout: 10s

scrape_configs:
  - job_name: "prometheus"
    metrics_path: /metrics
    scrape_interval: 5s
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: "webapp"
    metrics_path: /metrics
    scrape_interval: 5s
    static_configs:
      - targets: ['koa:8080']

  - job_name: "redis"
    metrics_path: /metrics
    scrape_interval: 5s
    static_configs:
      - targets: ['redis:6379']
